# Generated by Django 4.2.7 on 2023-11-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_cliente_produco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produco',
            new_name='Producto',
        ),
    ]
