# Generated by Django 4.2.7 on 2023-11-25 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_produco_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'clientes', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='update',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterOrderWithRespectTo(
            name='producto',
            order_with_respect_to='descripcion',
        ),
    ]
